### ISSUE TITLE
Export

### ISSUE THREAD

**Issue by demonicmetalcs** [Terricks/XAFBootstrap#21]
I am looking for the export to pdf / excel function is this not implemented or am i doing something wrong.

**Comment by Terricks** [comment]
It s not implemented

**Comment by demonicmetalcs** [comment]
Any tip on how to implement this?
I would like this feature and would not mind to implement it myself and share it with you.
But i don't know where to start

**Comment by Terricks** [comment]
There are several ways:
1) If standard export actions are based on model settings and collectionSource data in list editor (you will know it by discovering DX sources) - you can adapt it to XafB (maybe there are not implemented some interface functions or something like this - it's hard to say now why it s not displayed). But i think it's based on editor's export functionality (like ASPxGridView and it's Win analogue) - so, we couldn't use it, because it's only call control export functionality and returns result (but I'm not entirely sure about this, it need to be discovered)

2) Add your own ExportActions in controller, show it to user only if editor is assignable from XafBootstrapTableEditor, generate xlsx/pdf files on action's choice execute and return generated result  to user by Response (action must be synchronous to return data correctly, to do this check IsPostBackRequired in action model and use ResponseWriter.WriteFileToResponse(stream, nomefile)). In this way you can implement all logic in one controller.
Here is some links, that can help you:
https://www.devexpress.com/Support/Center/Question/Details/Q424812
https://www.devexpress.com/Support/Center/Question/Details/T126725
https://www.devexpress.com/Support/Center/Question/Details/Q583683

**Comment by Terricks** [comment]
The main work will be to write export logic, that generates files from collection source data. You can try to use existing DevEx functions/controls/libs (for example based on ASPxGridView or other controls).

**Comment by demonicmetalcs** [comment]
I have added the export function by adding the IExportable interface to XafBootstrapTableEditor

and the following code 

 public void OnExporting()
        {
          var printableEditor = new ASPxGridListEditor(ListView);
            printableEditor.CreateControls();
            printableEditor.Setup(collection,App);
            printableEditor.Grid.Visible = false;
            aspxGridViewExporter.Page = control.Page;
            control.Controls.Add(printableEditor.Grid);
        }
        private ASPxGridViewExporter aspxGridViewExporter;
        public List<ExportTarget> SupportedExportFormats { get {
                if(Printable == null) {
                    return new List<ExportTarget>();
                }
                else {
                    return new List<ExportTarget>() {
                        ExportTarget.Csv,
                        ExportTarget.Html,
                        ExportTarget.Image,
                        ExportTarget.Mht,
                        ExportTarget.Pdf,
                        ExportTarget.Rtf,
                        ExportTarget.Text,
                        ExportTarget.Xls,
                        ExportTarget.Xlsx
                    };
                }
            }}

```
    public IPrintable Printable
    {
        get { aspxGridViewExporter = new ASPxGridViewExporter(); return aspxGridViewExporter; }
    }

    public event EventHandler<PrintableChangedEventArgs> PrintableChanged;
```

**Comment by Terricks** [comment]
Thank you for your work and code, we'll research and add it to addon.

**Comment by Terricks** [comment]
Enhanced in release 15.2
